### ISSUE TITLE
How does "--max-resolution" argument work?

### ISSUE THREAD

**Issue by Malauch** [ecometrica/gdal2mbtiles#12]
Hi,
Can you tell me how does "--max-resolution MAX_RESOLUTION" argument work and what exactly resolution and what units should I use?

**Comment by hlwill** [comment]
Hi @Malauch,
Depending on what you are doing, you may be able to use [GDAL's mbtiles output format](http://www.gdal.org/frmt_mbtiles.html) instead of this library.

The `--max-resolution` is the maximum mbtiles zoom level that you wish to create tiles for. If you leave out the `--max-resolution` argument, gdal2mbtiles will automatically determine the closest zoom level to your input file and use that as the max. Depending on what you're using to display the mbtiles, I'd expect a maximum `MAX_RESOLUTION` of around 18, and lower max-resolutions for lower resolution data. 
The OpenStreetMap wiki has a [nice table of the different zoom levels](http://wiki.openstreetmap.org/wiki/Zoom_levels).
